productSample = [
    "Cho mình xem danh sách laptop",
    "Shop có điện thoại không?",
    "Tai nghe nào đang hot?",
    "Tôi cần tìm laptop rẻ nhất",
    "Các dòng laptop trong cửa hàng là gì?",
    "Thông tin sản phẩm MSI đâu?",
    "Tôi muốn mua laptop Asus, bạn có thể cho thêm thông tin không?",
    "Tai nghe nào thích hợp cho việc chơi game?",
    "Tôi muốn đặt một chiếc gaming laptop để chơi game, bạn có gợi ý nào không?",
    "Có loại laptop nào cho việc chơi game?",
    "Bạn có gợi ý laptop nào thích hợp để làm việc văn phòng không?",
    "Tôi muốn đặt chiếc laptop ASUS Zenbook 14 UX3407QA QD299WS để học và chơi, bạn có thể cho thêm thông tin không?",
    "Có laptop gì phù hợp để mua cho con vào đại học không?",
    "Laptop nào là best-seller tại cửa hàng của bạn?",
    "Tôi muốn mua Laptop Dell XPS 9350 XPS9350-U5IA165W11GR-FP để chúc mừng tốt nghiệp, bạn có gợi ý thêm không?",
    "Bạn có thể gợi ý một chiếc tai nghe xịn và rẻ phù hợp để tặng người yêu không?",
    "Tai nghe nào phù hợp chống ồn?",
    "Tôi muốn đặt một chiếc laptop để chơi game và thiết kế đồ hoạ.",
    "Bạn có loại tai nghe nào có chức năng chống ồn không?",
    "Bạn có loại laptop nào phù hợp cho xem phim không?",
    "Tôi muốn mua tai nghe Logitech G435 Lightspeed Wireless để tặng cho em trai.",
    "Bạn có thể tìm một chiếc laptop vẻ ngoài hiện đại không?",
    "Tôi cần laptop để làm việc, bạn có loại nào phù hợp không?",
    "Bạn có tai nghe nào phù hợp làm quà tặng cho đồng nghiệp không?",
    "Tôi cần đặt  Laptop gaming MSI Thin 15 B13UC 2044VN để chơi game.",
    "Bạn có thể gợi ý laptop nào phù hợp để thiết kế đồ hoạ không?",
    "Bạn có thể gợi ý một laptop đặc biệt với màu đen và cấu hình tốt không?",
    "giá của Laptop MSI Thin 15",
    "MSI Thin 15 giá bao nhiêu",
    "tôi muốn xem thông tin laptop gaming",
    "laptop nào chơi game tốt",
    "Laptop gaming MSI giá",
]

chitchatSample = [
     "Hi", "Hello", "Xin chào", "Chào bạn", "Bạn khỏe không", "Tôi muốn hỏi thăm",
    "Cảm ơn bạn", "Tạm biệt", "Có ai ở đó không?", "Shop mở cửa lúc mấy giờ?",
    "Bạn tên gì?", "Trợ lý ảo làm gì được?", "Giao tiếp với tôi nhé", "Chat chơi thôi",
    "Xin chao",
    "Hi",
    "Hello",
    "Chào bạn",
    "Hello shop",
    "Chàp shop",
    "Chào bạn! Hôm nay bạn thế nào?",
    "Bạn có thể kể cho tôi nghe về ngày hôm nay của bạn không?",
    "Bạn có thể giúp tôi thư giãn một chút được không?",
    "Bạn thích thời tiết như thế nào?",
    "Bạn làm việc ở đây bao lâu rồi?",
    "Bạn có thích nói chuyện với khách hàng không?",
    "Có điều gì thú vị bạn muốn chia sẻ không?",
    "Bạn có thể kể về lịch sử của cửa hàng không?",
    "Bạn nghĩ gì về mùa xuân?",
    "Bạn có lời khuyên nào để có một ngày vui vẻ không?",
    "Bạn có thể kể một câu chuyện vui không?",
    "Bạn thích làm gì vào thời gian rảnh?",
    "Bạn có biết món ăn nào ngon gần đây không?",
    "Bạn có sở thích nào đặc biệt không?",
    "Bạn có tin vào may mắn không?",
    "Bạn có thể dạy tôi cách chăm sóc hoa không?",
    "Công việc ở cửa hàng này có thú vị không?",
    "Bạn có gặp khách hàng thú vị nào không?",
    "Bạn thích làm việc một mình hay cùng đồng nghiệp?",
    "Bạn có thể chia sẻ một bí quyết thành công trong cuộc sống không?",
    "Bạn có thói quen nào đặc biệt vào buổi sáng không?",
    "Bạn có thể kể về một kỷ niệm đẹp khi làm việc ở đây không?",
    "Bạn nghĩ gì về việc chăm sóc cây cảnh?",
    "Bạn có thể đề xuất một quyển sách hay để đọc không?",
    "Bạn có thể kể về một khách hàng dễ thương mà bạn đã gặp không?",
    "Bạn có tin vào ý nghĩa của các loài hoa không?",
    "Bạn có thể giúp tôi chọn hoa cho một dịp đặc biệt không?"
]
